language: cpp
os: linux
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - valgrind


script:
  # скрипт сборки и тестирования проекта:
#  - cmake -DCMAKE_CXX_COMPILER="g++-6" ..
#  - make
#  - ctest -T memcheck
  - mkdir build
  - cd build
  - cmake ../tests -DCMAKE_BUILD_TYPE=Debug -DTARGET_CPU=x86
  - cmake --build . --target Tests
  - valgrind --tool=memcheck --xml=yes --xml-file=/tmp/valgrind --gen-suppressions=all --leak-check=full --track-origins=yes --vgdb=no ./Tests